// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAI8g3ISP45jl1XphhP9R7BuEWJZeOV8M',
    appId: '1:416100721092:ios:660a0529fb96e2bd10c491',
    messagingSenderId: '416100721092',
    projectId: 'tutor-247',
    storageBucket: 'tutor-247.firebasestorage.app',
    iosBundleId: 'com.example.tutorPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4uZT3sozxtfEO9wCioHgqfncLhdSoFmc',
    appId: '1:416100721092:web:8c264d0f7f1cc42c10c491',
    messagingSenderId: '416100721092',
    projectId: 'tutor-247',
    authDomain: 'tutor-247.firebaseapp.com',
    storageBucket: 'tutor-247.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4uZT3sozxtfEO9wCioHgqfncLhdSoFmc',
    appId: '1:416100721092:web:8c264d0f7f1cc42c10c491',
    messagingSenderId: '416100721092',
    projectId: 'tutor-247',
    authDomain: 'tutor-247.firebaseapp.com',
    storageBucket: 'tutor-247.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAI8g3ISP45jl1XphhP9R7BuEWJZeOV8M',
    appId: '1:416100721092:ios:660a0529fb96e2bd10c491',
    messagingSenderId: '416100721092',
    projectId: 'tutor-247',
    storageBucket: 'tutor-247.firebasestorage.app',
    iosBundleId: 'com.example.tutorPay',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfaFGOisbp5sCr1ALjaG1RASd-P7w0u2o',
    appId: '1:416100721092:android:be517f3fcda9ed1e10c491',
    messagingSenderId: '416100721092',
    projectId: 'tutor-247',
    storageBucket: 'tutor-247.firebasestorage.app',
  );

}